
[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # Proper MIME types for JavaScript files
    Content-Type = '''
    application/javascript; charset=utf-8
    '''
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
